/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'background': '#f9f9fc',
        'surface': '#f9f9fc',
        'surface-dim': '#dadadc',
        'surface-bright': '#f9f9fc',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f3f6',
        'surface-container': '#eeeef0',
        'surface-container-high': '#e8e8ea',
        'surface-container-highest': '#e2e2e5',
        'surface-variant': '#e2e2e5',
        'surface-tint': '#005db6',
        'on-surface': '#1a1c1e',
        'on-surface-variant': '#424752',
        'on-background': '#1a1c1e',
        'outline': '#727783',
        'outline-variant': '#c2c6d4',
        'inverse-surface': '#2f3133',
        'inverse-on-surface': '#f0f0f3',
        'primary': '#00478d',
        'on-primary': '#ffffff',
        'primary-container': '#005eb8',
        'on-primary-container': '#c8daff',
        'primary-fixed': '#d6e3ff',
        'primary-fixed-dim': '#a9c7ff',
        'on-primary-fixed': '#001b3d',
        'on-primary-fixed-variant': '#00468c',
        'inverse-primary': '#a9c7ff',
        'secondary': '#7d5700',
        'on-secondary': '#ffffff',
        'secondary-container': '#feb71a',
        'on-secondary-container': '#6b4b00',
        'secondary-fixed': '#ffdeaa',
        'secondary-fixed-dim': '#ffba2c',
        'on-secondary-fixed': '#271900',
        'on-secondary-fixed-variant': '#5f4100',
        'tertiary': '#940018',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#c10023',
        'on-tertiary-container': '#ffcecb',
        'tertiary-fixed': '#ffdad7',
        'tertiary-fixed-dim': '#ffb3af',
        'on-tertiary-fixed': '#410005',
        'on-tertiary-fixed-variant': '#930018',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        'label-md': ['"JetBrains Mono"', 'monospace'],
        'label-sm': ['"JetBrains Mono"', 'monospace'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'label-sm': ['10px', { lineHeight: '14px', letterSpacing: '0.05em', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
